const typographyTokens = {
  font_size_xs: "var(--font-size-xs)",
  font_size_sm: "var(--font-size-sm)",
  font_size_base: "var(--font-size-base)",
  font_size_lg: "var(--font-size-lg)",
  font_size_xl: "var(--font-size-xl)",
  font_size_2xl: "var(--font-size-2xl)",
  font_size_3xl: "var(--font-size-3xl)",
  font_size_4xl: "var(--font-size-4xl)",
  font_size_5xl: "var(--font-size-5xl)",
  font_size_6xl: "var(--font-size-6xl)",

  font_line_height_xs: "var(--font-line-height-xs)",
  font_line_height_sm: "var(--font-line-height-sm)",
  font_line_height_base: "var(--font-line-height-base)",
  font_line_height_lg: "var(--font-line-height-lg)",
  font_line_height_xl: "var(--font-line-height-xl)",
  font_line_height_2xl: "var(--font-line-height-2xl)",
  font_line_height_3xl: "var(--font-line-height-3xl)",
  font_line_height_4xl: "var(--font-line-height-4xl)",
  font_line_height_5xl: "var(--font-line-height-5xl)",
  font_line_height_6xl: "var(--font-line-height-6xl)",
  font_line_height_6xl_small: "var(--font-line-height-6xl-small)",

  font_weight_bold: "var(--bold)",
  font_weight_semibold: "var(--semibold)",
  font_weight_medium: "var(--medium)",
  font_weight_regular: "var(--regular)",

  font_letter_spacing_lg: "var(--font-letter-spacing-lg)",
  font_letter_spacing_xl: "var(--font-letter-spacing-xl)",
  font_letter_spacing_base: "var(--font-letter-spacing-base)",
  font_letter_spacing_sm: "var(--font-letter-spacing-sm)",
  font_letter_spacing_xs: "var(--font-letter-spacing-xs)",

  // v3 font size tokens
  font_size_900: "var(--font-size-900)",
  font_size_850: "var(--font-size-850)",
  font_size_800: "var(--font-size-800)",
  font_size_750: "var(--font-size-750)",
  font_size_700: "var(--font-size-700)",
  font_size_650: "var(--font-size-650)",
  font_size_600: "var(--font-size-600)",
  font_size_550: "var(--font-size-550)",
  font_size_500: "var(--font-size-500)",
  font_size_450: "var(--font-size-450)",
  font_size_400: "var(--font-size-400)",
  font_size_350: "var(--font-size-350)",
  font_size_300: "var(--font-size-300)",
  font_size_250: "var(--font-size-250)",
  font_size_200: "var(--font-size-200)",
  font_size_150: "var(--font-size-150)",

  line_height_900: "var(--line-height-900)",
  line_height_850: "var(--line-height-850)",
  line_height_800: "var(--line-height-800)",
  line_height_750: "var(--line-height-750)",
  line_height_700: "var(--line-height-700)",
  line_height_650: "var(--line-height-650)",
  line_height_600: "var(--line-height-600)",
  line_height_550: "var(--line-height-550)",
  line_height_500: "var(--line-height-500)",
  line_height_450: "var(--line-height-450)",
  line_height_400: "var(--line-height-400)",
  line_height_350: "var(--line-height-350)",
  line_height_300: "var(--line-height-300)",
  line_height_250: "var(--line-height-250)",
  line_height_200: "var(--line-height-200)",
  line_height_150: "var(--line-height-150)",

  letter_spacing_100: "var(--letter-spacing-100)"
};

export { typographyTokens };
